version: '3.1'

services:

  db:
    image: postgres:10.4-alpine
    container_name: people-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=people
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=passw0rd
    volumes:
      - people-db:/var/lib/postgresql/data
      
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 9090:8080

volumes:
  people-db: 